version: 2

workflows:
  version: 2
  production:
    jobs:
      - lint:
          context: GamePortal
      - build_and_push_image:
          context: GamePortal
          requires:
            - lint
      - deploy:
          context: GamePortal
          requires:
            - build_and_push_image

jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:v1.36-alpine
    steps:
      - checkout
      - run: golangci-lint run -v --timeout=5m
  # todo: Trigger this job only when changes appear in master and tag set
  # todo: Make job manual confirmation
  build_and_push_image:
    docker:
      - image: docker:20.10.3-git
    steps:
      - checkout
      - run: git branch
      - run: cat ./cmd/server/main.go
      - setup_remote_docker
      - run: docker build --no-cache -t ${DOCKER_REGISTRY_HOST}/forum-service:latest .
      - run: |
          alias aws='docker run --rm \
            -e AWS_ACCESS_KEY_ID=${STAGING_AWS_ACCESS_KEY_ID} \
            -e AWS_SECRET_ACCESS_KEY=${STAGING_AWS_SECRET_ACCESS_KEY} \
            -e AWS_DEFAULT_REGION=${STAGING_AWS_REGION} \
            amazon/aws-cli:2.1.28'
          aws ecr get-login-password --region ${STAGING_AWS_REGION} | docker login --username AWS --password-stdin ${DOCKER_REGISTRY_HOST}
      - run: docker push ${DOCKER_REGISTRY_HOST}/forum-service:latest
  # todo: Trigger this job only when changes appear in master and tag set
  # todo: Make job manual confirmation
  deploy:
    docker:
      - image: alpine:3.13.2
    steps:
      - checkout
      - setup_remote_docker
      - run: apk update && apk add openssh
      - run: |
          ssh -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} \
            "aws ecr get-login-password --region ${STAGING_AWS_REGION} | docker login --username AWS --password-stdin ${DOCKER_REGISTRY_HOST}; \
             docker stop forum-service; \
             docker rm forum-service; \
             docker rmi ${DOCKER_REGISTRY_HOST}/forum-service:latest; \
             docker run -d --restart unless-stopped -p 4000:4000 --name forum-service \
              -e POSTGRES_URL=${FORUM_SERVICE_CONN_URI} \
              -e FORUM_SERVICE_HOST=${FORUM_SERVICE_HOST} \
              -e FORUM_SERVICE_PORT=${FORUM_SERVICE_PORT} \
              -e GRPC_CONN_ADDR=${GRPC_CONN_ADDR} \
             ${DOCKER_REGISTRY_HOST}/forum-service:latest"
